pipeline {
    agent any
    
    environment {
        SERVICE_NAME = 'product-service'
        DOCKER_IMAGE = 'selimhorri/product-service-ecommerce-boot'
        DOCKER_TAG = "${env.BUILD_NUMBER}"
        KUBERNETES_NAMESPACE = 'ecommerce-prod'
        KUBECONFIG = '/var/jenkins_home/.kube/config'
        RELEASE_VERSION = "${env.BUILD_NUMBER}"
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                dir('product-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        
        stage('Unit Tests') {
            steps {
                dir('product-service') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    publishTestResults testResultsPattern: '**/target/surefire-reports/*.xml'
                }
            }
        }
        
        stage('Integration Tests') {
            steps {
                sh 'echo "Running integration tests..."'
                sh 'docker-compose -f compose.yml up -d'
                sh 'sleep 60'
                sh 'mvn test -Dtest=*IntegrationTest'
            }
            post {
                always {
                    sh 'docker-compose -f compose.yml down'
                }
            }
        }
        
        stage('Performance Tests') {
            steps {
                sh 'echo "Running performance tests with Locust..."'
                dir('performance-tests') {
                    sh 'locust -f locustfile.py --headless --users 50 --spawn-rate 5 --run-time 60 --host http://localhost:8080'
                }
            }
        }
        
        stage('Docker Build') {
            steps {
                dir('product-service') {
                    script {
                        def image = docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
                        docker.withRegistry('', 'docker-hub-credentials') {
                            image.push()
                            image.push('latest')
                        }
                    }
                }
            }
        }
        
        stage('Deploy to Kubernetes Production') {
            steps {
                script {
                    sh """
                        kubectl create namespace ${KUBERNETES_NAMESPACE} --dry-run=client -o yaml | kubectl apply -f -
                        kubectl set image deployment/product-service product-service=${DOCKER_IMAGE}:${DOCKER_TAG} -n ${KUBERNETES_NAMESPACE}
                        kubectl rollout status deployment/product-service -n ${KUBERNETES_NAMESPACE}
                    """
                }
            }
        }
        
        stage('Health Check') {
            steps {
                sh 'echo "Performing production health check..."'
                sh 'kubectl get pods -n ${KUBERNETES_NAMESPACE}'
                sh 'kubectl get services -n ${KUBERNETES_NAMESPACE}'
            }
        }
        
        stage('Generate Release Notes') {
            steps {
                script {
                    def releaseNotes = """
# Release Notes - Product Service v${RELEASE_VERSION}

## Changes in this release:
- Build Number: ${env.BUILD_NUMBER}
- Branch: ${env.BRANCH_NAME}
- Commit: ${env.GIT_COMMIT}
- Build Time: ${new Date()}

## Test Results:
- Unit Tests: ✅ Passed
- Integration Tests: ✅ Passed
- Performance Tests: ✅ Passed
- E2E Tests: ✅ Passed

## Deployment:
- Environment: Production
- Kubernetes Namespace: ${KUBERNETES_NAMESPACE}
- Docker Image: ${DOCKER_IMAGE}:${DOCKER_TAG}

## Rollback Instructions:
\`\`\`bash
kubectl rollout undo deployment/product-service -n ${KUBERNETES_NAMESPACE}
\`\`\`

Generated by Jenkins Pipeline on ${new Date()}
                    """
                    
                    writeFile file: 'RELEASE_NOTES.md', text: releaseNotes
                    archiveArtifacts artifacts: 'RELEASE_NOTES.md', fingerprint: true
                }
            }
        }
        
        stage('Create Git Tag') {
            steps {
                script {
                    sh """
                        git config user.email "jenkins@example.com"
                        git config user.name "Jenkins"
                        git tag -a "v${RELEASE_VERSION}" -m "Release version ${RELEASE_VERSION}"
                        git push origin "v${RELEASE_VERSION}"
                    """
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
        success {
            echo 'Production deployment completed successfully!'
            emailext (
                subject: "✅ Deployment Successful - Product Service v${RELEASE_VERSION}",
                body: "Product Service v${RELEASE_VERSION} has been successfully deployed to production.",
                to: "devops@example.com"
            )
        }
        failure {
            echo 'Production deployment failed!'
            emailext (
                subject: "❌ Deployment Failed - Product Service v${RELEASE_VERSION}",
                body: "Product Service v${RELEASE_VERSION} deployment to production has failed. Please check the logs.",
                to: "devops@example.com"
            )
        }
    }
}







