apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce-prod
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==  # base64 encoded "root"
  SPRING_DATASOURCE_PASSWORD: cm9vdA==  # base64 encoded "root"
  JWT_SECRET: bXlzZWNyZXRrZXk=  # base64 encoded "mysecretkey"
  ENCRYPTION_KEY: bXllbmNyeXB0aW9ua2V5  # base64 encoded "myencryptionkey"







