@echo off
echo ================================================
echo Creating Jenkins Pipeline Jobs with XML
echo ================================================

REM Crear jobs de pipeline usando XML válido
echo Creating pipeline jobs...

REM User Service Jobs
echo Creating user-service-dev...
echo ^<?xml version="1.0" encoding="UTF-8"?^>^<flow-definition plugin="workflow-job@2.42"^>^<description^>User Service Development Pipeline^</description^>^<keepDependencies^>false^</keepDependencies^>^<properties^>^<jenkins.model.BuildDiscarderProperty^>^<strategy class="hudson.tasks.LogRotator"^>^<daysToKeep^>10^</daysToKeep^>^<numToKeep^>5^</numToKeep^>^<artifactDaysToKeep^>-1^</artifactDaysToKeep^>^<artifactNumToKeep^>-1^</artifactNumToKeep^>^</strategy^>^</jenkins.model.BuildDiscarderProperty^>^</properties^>^<definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps@2.90"^>^<scm class="hudson.plugins.git.GitSCM" plugin="git@4.8.3"^>^<configVersion^>2^</configVersion^>^<userRemoteConfigs^>^<hudson.plugins.git.UserRemoteConfig^>^<url^>file:///C:/Users/gdjhb/Downloads/ecommerce-microservice-backend-app^</url^>^</hudson.plugins.git.UserRemoteConfig^>^</userRemoteConfigs^>^<branches^>^<hudson.plugins.git.BranchSpec^>^<name^>*/dev^</name^>^</hudson.plugins.git.BranchSpec^>^</branches^>^<doGenerateSubmoduleConfigurations^>false^</doGenerateSubmoduleConfigurations^>^<submoduleCfg class="list"^>^</submoduleCfg^>^<extensions^>^</extensions^>^</scm^>^<scriptPath^>jenkins/pipelines/user-service-dev.Jenkinsfile^</scriptPath^>^<lightweight^>false^</lightweight^>^</definition^>^<triggers^>^</triggers^>^<disabled^>false^</disabled^>^</flow-definition^> | java -jar jenkins-cli.jar -s http://localhost:8080 -auth admin:admin123 create-job "user-service-dev"

echo Creating user-service-stage...
echo ^<?xml version="1.0" encoding="UTF-8"?^>^<flow-definition plugin="workflow-job@2.42"^>^<description^>User Service Staging Pipeline^</description^>^<keepDependencies^>false^</keepDependencies^>^<properties^>^<jenkins.model.BuildDiscarderProperty^>^<strategy class="hudson.tasks.LogRotator"^>^<daysToKeep^>10^</daysToKeep^>^<numToKeep^>5^</numToKeep^>^<artifactDaysToKeep^>-1^</artifactDaysToKeep^>^<artifactNumToKeep^>-1^</artifactNumToKeep^>^</strategy^>^</jenkins.model.BuildDiscarderProperty^>^</properties^>^<definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps@2.90"^>^<scm class="hudson.plugins.git.GitSCM" plugin="git@4.8.3"^>^<configVersion^>2^</configVersion^>^<userRemoteConfigs^>^<hudson.plugins.git.UserRemoteConfig^>^<url^>file:///C:/Users/gdjhb/Downloads/ecommerce-microservice-backend-app^</url^>^</hudson.plugins.git.UserRemoteConfig^>^</userRemoteConfigs^>^<branches^>^<hudson.plugins.git.BranchSpec^>^<name^>*/stage^</name^>^</hudson.plugins.git.BranchSpec^>^</branches^>^<doGenerateSubmoduleConfigurations^>false^</doGenerateSubmoduleConfigurations^>^<submoduleCfg class="list"^>^</submoduleCfg^>^<extensions^>^</extensions^>^</scm^>^<scriptPath^>jenkins/pipelines/user-service-stage.Jenkinsfile^</scriptPath^>^<lightweight^>false^</lightweight^>^</definition^>^<triggers^>^</triggers^>^<disabled^>false^</disabled^>^</flow-definition^> | java -jar jenkins-cli.jar -s http://localhost:8080 -auth admin:admin123 create-job "user-service-stage"

echo Creating user-service-master...
echo ^<?xml version="1.0" encoding="UTF-8"?^>^<flow-definition plugin="workflow-job@2.42"^>^<description^>User Service Production Pipeline^</description^>^<keepDependencies^>false^</keepDependencies^>^<properties^>^<jenkins.model.BuildDiscarderProperty^>^<strategy class="hudson.tasks.LogRotator"^>^<daysToKeep^>10^</daysToKeep^>^<numToKeep^>5^</numToKeep^>^<artifactDaysToKeep^>-1^</artifactDaysToKeep^>^<artifactNumToKeep^>-1^</artifactNumToKeep^>^</strategy^>^</jenkins.model.BuildDiscarderProperty^>^</properties^>^<definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps@2.90"^>^<scm class="hudson.plugins.git.GitSCM" plugin="git@4.8.3"^>^<configVersion^>2^</configVersion^>^<userRemoteConfigs^>^<hudson.plugins.git.UserRemoteConfig^>^<url^>file:///C:/Users/gdjhb/Downloads/ecommerce-microservice-backend-app^</url^>^</hudson.plugins.git.UserRemoteConfig^>^</userRemoteConfigs^>^<branches^>^<hudson.plugins.git.BranchSpec^>^<name^>*/master^</name^>^</hudson.plugins.git.BranchSpec^>^</branches^>^<doGenerateSubmoduleConfigurations^>false^</doGenerateSubmoduleConfigurations^>^<submoduleCfg class="list"^>^</submoduleCfg^>^<extensions^>^</extensions^>^</scm^>^<scriptPath^>jenkins/pipelines/user-service-master.Jenkinsfile^</scriptPath^>^<lightweight^>false^</lightweight^>^</definition^>^<triggers^>^</triggers^>^<disabled^>false^</disabled^>^</flow-definition^> | java -jar jenkins-cli.jar -s http://localhost:8080 -auth admin:admin123 create-job "user-service-master"

echo ================================================
echo Jenkins jobs created successfully!
echo ================================================
echo Access Jenkins at: http://localhost:8080
echo Username: admin
echo Password: admin123
echo ================================================
